### ISSUE TITLE
logViewer does not report all logs when launched from Astor

### ISSUE THREAD

**Issue by mrosanes** [tango-controls/LogViewer#2]
Hi,

I have a DS that is executing a command on another machine thanks to ssh and subprocess.Popen. I am logging the errors on logViewer.

When the DS is executed from the terminal the whole error log is correctly displayed in logViewer [whole_message.txt](https://github.com/tango-controls/LogViewer/files/2639397/whole_message.txt). 

However when the DS is launched from astor, for some reason, only a small part of the error log is displayed in logViewer.
[part_message.txt](https://github.com/tango-controls/LogViewer/files/2639396/part_message.txt)

It would be possible to see the whole error log when launching the DS from astor as well?

**Comment by Pascal-Verdier** [comment]
Hi
The problem is not related to LogViewer, but to the file generated by your server through the Python API or to your startup script.
If I do it with a C++ server, started or not by the Starter, I have file with same look.
But these files do not look like yours.

It looks like :
`<log4j:event logger="pv/dummy/1-1" timestamp="1543842722451" level="DEBUG" thread="140039530989312">
<log4j:message><![CDATA[Dummy::always_executed_hook()  pv/dummy/1-1]]></log4j:message>
<log4j:NDC><![CDATA[]]></log4j:NDC>
</log4j:event>

<log4j:event logger="pv/dummy/1-1" timestamp="1543842722451" level="DEBUG" thread="140039530989312">
<log4j:message><![CDATA[Dummy::read_attr_hardware(vector<long> &attr_list) entering... ]]></log4j:message>
<log4j:NDC><![CDATA[]]></log4j:NDC>
</log4j:event>

<log4j:event logger="pv/dummy/1-1" timestamp="1543842722451" level="DEBUG" thread="140039530989312">
<log4j:message><![CDATA[Dummy::read_Value(Tango::Attribute &attr) entering... ]]></log4j:message>
<log4j:NDC><![CDATA[]]></log4j:NDC>
</log4j:event>
`
I have no idea how your files are generated, but they are not LogViewer compatible.
Regards
Pascal

**Comment by mrosanes** [comment]
Salut Pascal,

Sorry, the files attached were only a copy paste of the logviewer window where the messages are displayed.

Here after I attach the log file generated when I run the DS from the terminal:
[bl09_ct_txmautopreprocessing_from_terminal.log](https://github.com/tango-controls/LogViewer/files/2639908/bl09_ct_txmautopreprocessing_from_terminal.log)

and the log file when I run it from astor:
[bl09_ct_txmautopreprocessing_from_astor.log](https://github.com/tango-controls/LogViewer/files/2639912/bl09_ct_txmautopreprocessing_from_astor.log)

When running the DS from the terminal, more information about the error is appearing in the log file, compared to running it from astor.


The DS used is the following one:
[txmautopreprocessing.txt](https://github.com/tango-controls/LogViewer/files/2639914/txmautopreprocessing.txt)


Merci pour l'aide,
marc

**Comment by Pascal-Verdier** [comment]
Hola Marc
I am sorry, I do not see any difference between the 2 log files. Except time stamp of course.
What kind of difference you mean ?
![bl09](https://user-images.githubusercontent.com/19665928/49425410-c9a8a900-f79d-11e8-9ce3-5b864c877c1f.PNG)
![bl09-astor](https://user-images.githubusercontent.com/19665928/49425414-cca39980-f79d-11e8-8b12-75bd517c6634.PNG)

**Comment by mrosanes** [comment]
The difference can be seen in the 'log details' window from the logviewer (or doing a kompare of both .log files): is inside the messages of the Error logs: running the DS from terminal logs more details about the error, than running it from astor.
![log_ds_run_from_terminal](https://user-images.githubusercontent.com/1327426/49427259-2490cf00-f7a3-11e8-93ac-f4fe0ef1530e.jpeg)
![log_ds_run_from_astor](https://user-images.githubusercontent.com/1327426/49427265-28245600-f7a3-11e8-8fd1-9ec909d0a4b0.jpeg)

**Comment by mrosanes** [comment]
Salut Pascal,

In fact, it is not much a problem coming from the logViewer. The problem is already existing in the '.log' files themselves: the two stored logs are not equivalent; one contains more information than the other about the errors.

I don't know if I should better report this problem to Tango directly, to Astor, or in another place.
